server:
  port: 8080
  # Latency warning thresholds (in milliseconds)
  # Increase these if your Redis is in a different region/network
  processing_latency_warn_ms: 50  # Default: 50ms
  store_latency_warn_ms: 20       # Default: 20ms (increase to 200 for remote Redis)

redis:
  # Leave addr empty to use in-memory storage instead of Redis
  addr: ""  # Set to "localhost:6379" to use Redis
  password: ""
  db: 0

logging:
  level: debug
  format: json
  production: true  # Set to true to only show errors/warnings
  ticker_updates: false  # Set to false to disable verbose ticker update logs

# Use the ACTUAL symbol names for each exchange
# Binance uses 1000SHIB, 1000PEPE for small-value tokens
# Bybit uses SHIB1000, 1000PEPE
# Others use regular SHIB, PEPE

exchanges:
  binance:
    enabled: true
    ws_url: wss://fstream.binance.com
    symbols:
      - btc-usdt
      - eth-usdt
      - xrp-usdt
      - bnb-usdt
      - sol-usdt
      - doge-usdt
      - ada-usdt
      - trx-usdt
      - link-usdt
      - xlm-usdt
      - sui-usdt
      - uni-usdt
      - ena-usdt
      - 1000shib-usdt    # Binance futures symbol
      - 1000pepe-usdt    # Binance futures symbol

  okx:
    enabled: true
    ws_url: wss://ws.okx.com:8443/ws/v5/public
    symbols:
      - btc-usdt
      - eth-usdt
      - xrp-usdt
      - bnb-usdt
      - sol-usdt
      - doge-usdt
      - ada-usdt
      - trx-usdt
      - link-usdt
      - xlm-usdt
      - sui-usdt
      - uni-usdt
      - ena-usdt
      - shib-usdt        # OKX uses regular SHIB
      - pepe-usdt        # OKX uses regular PEPE

  bybit:
    enabled: true
    ws_url: wss://stream.bybit.com/v5/public/linear
    symbols:
      - btc-usdt
      - eth-usdt
      - xrp-usdt
      - bnb-usdt
      - sol-usdt
      - doge-usdt
      - ada-usdt
      - trx-usdt
      - link-usdt
      - xlm-usdt
      - sui-usdt
      - uni-usdt
      - ena-usdt
      - shib1000-usdt    # Bybit's actual symbol (weird format!)
      - 1000pepe-usdt    # Bybit's actual symbol

  bitget:
    enabled: true
    ws_url: wss://ws.bitget.com/mix/v1/stream
    symbols:
      - btc-usdt
      - eth-usdt
      - xrp-usdt
      - bnb-usdt
      - sol-usdt
      - doge-usdt
      - ada-usdt
      - trx-usdt
      - link-usdt
      - xlm-usdt
      - sui-usdt
      - uni-usdt
      - ena-usdt
      - shib-usdt        # Bitget uses regular SHIB
      - pepe-usdt        # Bitget uses regular PEPE

  gate:
    enabled: true
    ws_url: wss://fx-ws.gateio.ws/v4/ws/usdt
    symbols:
      - btc-usdt
      - eth-usdt
      - xrp-usdt
      - bnb-usdt
      - sol-usdt
      - doge-usdt
      - ada-usdt
      - trx-usdt
      - link-usdt
      - xlm-usdt
      - sui-usdt
      - uni-usdt
      - ena-usdt
      - shib-usdt        # Gate uses regular SHIB
      - pepe-usdt        # Gate uses regular PEPE
