# Production configuration for ticker-service-v2

server:
  port: 8080

redis:
  # Configure Redis for production, or leave addr empty for in-memory storage
  addr: ""

logging:
  level: info
  format: json
  production: true     # Only show errors/warnings
  ticker_updates: false  # Disable verbose ticker logs

exchanges:
  binance:
    enabled: true
    ws_url: wss://fstream.binance.com
    symbols:
      - btc-usdt
      - eth-usdt
      - xrp-usdt
      - bnb-usdt
      - sol-usdt
      - doge-usdt
      - ada-usdt
      - trx-usdt
      - link-usdt
      - xlm-usdt
      - sui-usdt
      - uni-usdt
      - ena-usdt
      - 1000shib-usdt
      - 1000pepe-usdt

  okx:
    enabled: true
    ws_url: wss://ws.okx.com:8443/ws/v5/public
    symbols:
      - btc-usdt
      - eth-usdt
      - xrp-usdt
      - bnb-usdt
      - sol-usdt
      - doge-usdt
      - ada-usdt
      - trx-usdt
      - link-usdt
      - xlm-usdt
      - sui-usdt
      - uni-usdt
      - ena-usdt
      - shib-usdt
      - pepe-usdt

  bybit:
    enabled: true
    ws_url: wss://stream.bybit.com/v5/public/linear
    symbols:
      - btc-usdt
      - eth-usdt
      - xrp-usdt
      - bnb-usdt
      - sol-usdt
      - doge-usdt
      - ada-usdt
      - trx-usdt
      - link-usdt
      - xlm-usdt
      - sui-usdt
      - uni-usdt
      - ena-usdt
      - shib1000-usdt
      - 1000pepe-usdt

  bitget:
    enabled: true
    ws_url: wss://ws.bitget.com/mix/v1/stream
    symbols:
      - btc-usdt
      - eth-usdt
      - xrp-usdt
      - bnb-usdt
      - sol-usdt
      - doge-usdt
      - ada-usdt
      - trx-usdt
      - link-usdt
      - xlm-usdt
      - sui-usdt
      - uni-usdt
      - ena-usdt
      - shib-usdt
      - pepe-usdt

  gate:
    enabled: true
    ws_url: wss://fx-ws.gateio.ws/v4/ws/usdt
    symbols:
      - btc-usdt
      - eth-usdt
      - xrp-usdt
      - bnb-usdt
      - sol-usdt
      - doge-usdt
      - ada-usdt
      - trx-usdt
      - link-usdt
      - xlm-usdt
      - sui-usdt
      - uni-usdt
      - ena-usdt
      - shib-usdt
      - pepe-usdt
