version: "3.3"

services:
  app:
    image: ticker-service-v2-dev
    container_name: ticker-service-v2-dev
    restart: unless-stopped

    # Graceful shutdown configuration - give the app 30s to complete shutdown
    stop_grace_period: 30s
    stop_signal: SIGTERM

    # Configure ulimit to support many WebSocket connections
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      nproc:
        soft: 65536
        hard: 65536

    # Resource limits
    deploy:
      resources:
        limits:
          memory: 2G

    # System configuration optimization
    sysctls:
      - net.core.somaxconn=65535
      - net.ipv4.tcp_max_syn_backlog=65535
      - net.ipv4.tcp_fin_timeout=30
      - net.ipv4.tcp_keepalive_time=1200
      - net.ipv4.tcp_max_tw_buckets=180000

    # Mount config file
    volumes:
      - ./config.yaml:/app/config.yaml:ro

    # Use development config
    environment:
      - CONFIG_FILE=config.yaml

    # Port mapping - HTTP and gRPC
    ports:
      - "8091:8080"  # HTTP API
      - "50051:50051"  # gRPC API

    # Network configuration - use shared network for service communication
    networks:
      - dddd-network

# Define shared network for inter-service communication
networks:
  dddd-network:
    external: true
